version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: aitf-backend
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        # Make the frontend talk to the backend service name inside Docker
        REACT_APP_API_BASE_URL: http://backend:5000/api
    container_name: aitf-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped
